# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction

In [1]:
import numpy as np
import pandas as pd
ionosp_data = pd.read_csv("ionosphere_data.csv")

In [2]:
ionosp_data.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [3]:
train_Data = ionosp_data.sample(frac=1)

In [4]:
label_ohc = {"g": 0, "b":1}
train_Data["label1"] = train_Data.label.map(label_ohc)

In [6]:
train_Data.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label,label1
65,1,0,0.84783,0.10598,1.00000,0.39130,1.00000,-1.00000,0.66938,0.08424,...,1.00000,0.15942,0.37681,-0.01947,1.00000,0.22464,1.00000,0.37409,b,1
188,0,0,-1.00000,1.00000,-1.00000,-1.00000,0.00000,0.00000,-1.00000,1.00000,...,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,0.00000,0.00000,b,1
119,1,0,0.86889,-0.07111,1.00000,-0.02494,1.00000,-0.06889,0.87778,0.00222,...,1.00000,-0.14162,0.82222,-0.14667,1.00000,-0.15609,1.00000,-0.44222,g,0
50,1,0,0.84134,-0.18362,0.43644,0.02919,0.93421,-0.00267,0.87947,0.13795,...,0.93358,-0.01158,0.61582,-0.32298,0.84463,-0.25706,0.93323,-0.01425,g,0
14,1,0,1.00000,0.07380,1.00000,0.03420,1.00000,-0.05563,1.00000,0.08764,...,1.00000,0.36743,0.95603,0.48641,1.00000,0.32492,1.00000,0.46712,g,0

In [7]:
trainData =train_Data.drop(['label'], axis = 1)

In [8]:
trainData.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label1
65,1,0,0.84783,0.10598,1.00000,0.39130,1.00000,-1.00000,0.66938,0.08424,...,-0.33333,1.00000,0.15942,0.37681,-0.01947,1.00000,0.22464,1.00000,0.37409,1
188,0,0,-1.00000,1.00000,-1.00000,-1.00000,0.00000,0.00000,-1.00000,1.00000,...,-1.00000,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,0.00000,0.00000,1
119,1,0,0.86889,-0.07111,1.00000,-0.02494,1.00000,-0.06889,0.87778,0.00222,...,0.03556,1.00000,-0.14162,0.82222,-0.14667,1.00000,-0.15609,1.00000,-0.44222,0
50,1,0,0.84134,-0.18362,0.43644,0.02919,0.93421,-0.00267,0.87947,0.13795,...,-0.02778,0.93358,-0.01158,0.61582,-0.32298,0.84463,-0.25706,0.93323,-0.01425,0
14,1,0,1.00000,0.07380,1.00000,0.03420,1.00000,-0.05563,1.00000,0.08764,...,0.20033,1.00000,0.36743,0.95603,0.48641,1.00000,0.32492,1.00000,0.46712,0

In [10]:
trainData =trainData.astype("float32")

In [11]:
data =trainData.to_numpy()

In [12]:
data.shape

(351, 35)

In [13]:
training = data[0:210]
testing = data[210:]

In [14]:
print(training.shape)
print(testing.shape)

(210, 35)
(141, 35)

In [15]:
training_features = training[:,0:-1]
training_labels = training[:,-1]
testing_features = testing[:,0:-1]
testing_labels = testing[:,-1]

In [16]:
print(training_features.shape)
print(training_labels.shape)

(210, 34)
(210,)

In [17]:
training_features[0].shape

(34,)

In [18]:
testing_labels = pd.get_dummies(testing_labels)

In [19]:
training_labels = pd.get_dummies(training_labels)

In [20]:
training_labels.head()

   0.0  1.0
0    0    1
1    0    1
2    1    0
3    1    0
4    1    0

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.optimizers import Adam, SGD

In [22]:
model = Sequential()
model.add(Dense(25, activation="relu", input_shape= (34,)))
model.add(Dropout(0.2))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation="sigmoid"))

In [23]:
model.compile(optimizer=Adam(),
              loss = "binary_crossentropy", 
              metrics=["accuracy"])

In [24]:
history = model.fit(training_features, training_labels, 
                    epochs=45, 
                    batch_size = 15, 
                    validation_data=(testing_features, testing_labels))

Epoch 1/45
14/14 [==============================] - 5s 273ms/step - loss: 0.6790 - accuracy: 0.6961 - val_loss: 0.6740 - val_accuracy: 0.6099
Epoch 2/45
14/14 [==============================] - 0s 25ms/step - loss: 0.6340 - accuracy: 0.6396 - val_loss: 0.6579 - val_accuracy: 0.6099
Epoch 3/45
14/14 [==============================] - 0s 19ms/step - loss: 0.6374 - accuracy: 0.6649 - val_loss: 0.6444 - val_accuracy: 0.6170
Epoch 4/45
14/14 [==============================] - 0s 19ms/step - loss: 0.6617 - accuracy: 0.7112 - val_loss: 0.6317 - val_accuracy: 0.6312
Epoch 5/45
14/14 [==============================] - 0s 17ms/step - loss: 0.6169 - accuracy: 0.6484 - val_loss: 0.6205 - val_accuracy: 0.6383
Epoch 6/45
14/14 [==============================] - 0s 20ms/step - loss: 0.6123 - accuracy: 0.7070 - val_loss: 0.6137 - val_accuracy: 0.6454
Epoch 7/45
14/14 [==============================] - 0s 19ms/step - loss: 0.5359 - accuracy: 0.7360 - val_loss: 0.6051 - val_accuracy: 0.6667
Epoch 8/45
14/14 [==============================] - 0s 25ms/step - loss: 0.5049 - accuracy: 0.7489 - val_loss: 0.5964 - val_accuracy: 0.6809
Epoch 9/45
14/14 [==============================] - 0s 17ms/step - loss: 0.5353 - accuracy: 0.7816 - val_loss: 0.5893 - val_accuracy: 0.6879
Epoch 10/45
14/14 [==============================] - 0s 20ms/step - loss: 0.5434 - accuracy: 0.7113 - val_loss: 0.5797 - val_accuracy: 0.7021
Epoch 11/45
14/14 [==============================] - 0s 16ms/step - loss: 0.5362 - accuracy: 0.7285 - val_loss: 0.5714 - val_accuracy: 0.7163
Epoch 12/45
14/14 [==============================] - 0s 16ms/step - loss: 0.4803 - accuracy: 0.7756 - val_loss: 0.5636 - val_accuracy: 0.7376
Epoch 13/45
14/14 [==============================] - 0s 19ms/step - loss: 0.5074 - accuracy: 0.7735 - val_loss: 0.5564 - val_accuracy: 0.7518
Epoch 14/45
14/14 [==============================] - 0s 29ms/step - loss: 0.4663 - accuracy: 0.8126 - val_loss: 0.5512 - val_accuracy: 0.7801
Epoch 15/45
14/14 [==============================] - 0s 19ms/step - loss: 0.4298 - accuracy: 0.8434 - val_loss: 0.5474 - val_accuracy: 0.7801
Epoch 16/45
14/14 [==============================] - 0s 17ms/step - loss: 0.4756 - accuracy: 0.7967 - val_loss: 0.5410 - val_accuracy: 0.7872
Epoch 17/45
14/14 [==============================] - 0s 19ms/step - loss: 0.4445 - accuracy: 0.8254 - val_loss: 0.5356 - val_accuracy: 0.7943
Epoch 18/45
14/14 [==============================] - 0s 11ms/step - loss: 0.4184 - accuracy: 0.8310 - val_loss: 0.5269 - val_accuracy: 0.8085
Epoch 19/45
14/14 [==============================] - 0s 7ms/step - loss: 0.4044 - accuracy: 0.8490 - val_loss: 0.5204 - val_accuracy: 0.8085
Epoch 20/45
14/14 [==============================] - 0s 12ms/step - loss: 0.3898 - accuracy: 0.8906 - val_loss: 0.5179 - val_accuracy: 0.8085
Epoch 21/45
14/14 [==============================] - 0s 10ms/step - loss: 0.3444 - accuracy: 0.9297 - val_loss: 0.5183 - val_accuracy: 0.8085
Epoch 22/45
14/14 [==============================] - 0s 8ms/step - loss: 0.3242 - accuracy: 0.9012 - val_loss: 0.5074 - val_accuracy: 0.8369
Epoch 23/45
14/14 [==============================] - 0s 10ms/step - loss: 0.3734 - accuracy: 0.8926 - val_loss: 0.4953 - val_accuracy: 0.8369
Epoch 24/45
14/14 [==============================] - 0s 12ms/step - loss: 0.3770 - accuracy: 0.9234 - val_loss: 0.4874 - val_accuracy: 0.8440
Epoch 25/45
14/14 [==============================] - 0s 25ms/step - loss: 0.3300 - accuracy: 0.8870 - val_loss: 0.4818 - val_accuracy: 0.8440
Epoch 26/45
14/14 [==============================] - 0s 14ms/step - loss: 0.3185 - accuracy: 0.9042 - val_loss: 0.4761 - val_accuracy: 0.8511
Epoch 27/45
14/14 [==============================] - 0s 14ms/step - loss: 0.3337 - accuracy: 0.8768 - val_loss: 0.4749 - val_accuracy: 0.8440
Epoch 28/45
14/14 [==============================] - 0s 15ms/step - loss: 0.3143 - accuracy: 0.9297 - val_loss: 0.4748 - val_accuracy: 0.8511
Epoch 29/45
14/14 [==============================] - 0s 24ms/step - loss: 0.2751 - accuracy: 0.9082 - val_loss: 0.4818 - val_accuracy: 0.8440
Epoch 30/45
14/14 [==============================] - 0s 13ms/step - loss: 0.2726 - accuracy: 0.9408 - val_loss: 0.4705 - val_accuracy: 0.8582
Epoch 31/45
14/14 [==============================] - 0s 12ms/step - loss: 0.2774 - accuracy: 0.9375 - val_loss: 0.4586 - val_accuracy: 0.8652
Epoch 32/45
14/14 [==============================] - 0s 11ms/step - loss: 0.2444 - accuracy: 0.9478 - val_loss: 0.4638 - val_accuracy: 0.8511
Epoch 33/45
14/14 [==============================] - 0s 11ms/step - loss: 0.2378 - accuracy: 0.9256 - val_loss: 0.4650 - val_accuracy: 0.8511
Epoch 34/45
14/14 [==============================] - 0s 11ms/step - loss: 0.2298 - accuracy: 0.9493 - val_loss: 0.4550 - val_accuracy: 0.8723
Epoch 35/45
14/14 [==============================] - 0s 12ms/step - loss: 0.2362 - accuracy: 0.9310 - val_loss: 0.4609 - val_accuracy: 0.8582
Epoch 36/45
14/14 [==============================] - 0s 10ms/step - loss: 0.2344 - accuracy: 0.9288 - val_loss: 0.4581 - val_accuracy: 0.8582
Epoch 37/45
14/14 [==============================] - 0s 11ms/step - loss: 0.2310 - accuracy: 0.9341 - val_loss: 0.4513 - val_accuracy: 0.8723
Epoch 38/45
14/14 [==============================] - 0s 7ms/step - loss: 0.2608 - accuracy: 0.9554 - val_loss: 0.4450 - val_accuracy: 0.8652
Epoch 39/45
14/14 [==============================] - 0s 6ms/step - loss: 0.2506 - accuracy: 0.9165 - val_loss: 0.4479 - val_accuracy: 0.8723
Epoch 40/45
14/14 [==============================] - 0s 10ms/step - loss: 0.1724 - accuracy: 0.9250 - val_loss: 0.4775 - val_accuracy: 0.8582
Epoch 41/45
14/14 [==============================] - 0s 9ms/step - loss: 0.1799 - accuracy: 0.9487 - val_loss: 0.4701 - val_accuracy: 0.8582
Epoch 42/45
14/14 [==============================] - 0s 8ms/step - loss: 0.2163 - accuracy: 0.9366 - val_loss: 0.4543 - val_accuracy: 0.8652
Epoch 43/45
14/14 [==============================] - 0s 8ms/step - loss: 0.1857 - accuracy: 0.9383 - val_loss: 0.4618 - val_accuracy: 0.8652
Epoch 44/45
14/14 [==============================] - 0s 8ms/step - loss: 0.1595 - accuracy: 0.9753 - val_loss: 0.4728 - val_accuracy: 0.8582
Epoch 45/45
14/14 [==============================] - 0s 9ms/step - loss: 0.2029 - accuracy: 0.9050 - val_loss: 0.4732 - val_accuracy: 0.8582

In [25]:
for_predict = pd.read_csv("ionosphere_data.csv",)

In [26]:
for_predict.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [28]:
for_predict['predict']=training_labels.columns.take(np.argmax(model.predict(for_predict.loc[:,'feature1':'feature34']), axis=1))
predict_colnm = {0.0: "Good", 1.0:"Bad"}
for_predict["predict1"] = for_predict.predict.map(predict_colnm)

In [29]:
for_predict.drop(columns=["predict"])

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label,predict1
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g,Good
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b,Bad
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g,Good
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b,Bad
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g,Good
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g,Good
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g,Good
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g,Good
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g,Good